### ISSUE TITLE
Cannot see the calendar

### ISSUE THREAD

**Issue by jmoscatiello** [traex/CalendarListview#26]
Hey guys,

   I downloaded the sample and attempted to integrate this view into my project but I cannot actually see the view. Is this a styling thing?

Please advise.

**Comment by ziyaozou** [comment]
plz modify the getMaxYear() function in MainActivity.java file, making its return value >= 2016

**Comment by songzhiyong** [comment]
have you call setController(...)?

**Comment by jmoscatiello** [comment]
@ziyaozou that solved it for me thanks
