### ISSUE TITLE
No way to provide custom adapter

### ISSUE THREAD

**Issue by apkelly** [traex/CalendarListview#6]
If I extend the DayPickerView with a view to overriding the setAdapter method, I can't provide my own adapter as the mController and typedArray attributes are private, so I have no way of accessing them to pass to my own adapter.

**Comment by apkelly** [comment]
Hi, is this closed+fixed or closed+will-not-fix?

**Comment by traex** [comment]
Hi :) this is fixed in the v1.2.3. Can you try and give me some feedbacks ?
