### ISSUE TITLE
When can I call getSelectedDays()?

### ISSUE THREAD

**Issue by apkelly** [traex/CalendarListview#7]
There doesn't seem to be an API callback that lets me know when a date range has been selected. I can see in the controller that there is a callback when a date is selected, but internally this could be the firstDate or lastDate which will be populated into selectedDays.

Apart from constantly checking if first != null && last != null, how can I know when a range is available?

**Comment by apkelly** [comment]
Hi, is this closed+fixed or closed+will-not-fix?

**Comment by traex** [comment]
Hi :) this is fixed in the v1.2.3. Can you try and give me some feedbacks ?
